django-tastypie/django-tastypie

tastypie/resources.py, tests/related_resource/api/resources.py, tests/related_resource/models.py, tests/related_resource/tests.py, tests/testcases.py
When issuing a PUT request on a prefetched field, the old data is returned.
A failing test is included. I'll try to fix this myself, but any tips are appreciated :smile: 
**Resource:**
```
class Meta:
always_return_data = True
queryset = Forum.objects.prefetch_related('moderators', 'members')
```
**Pseudo-Code:**
```
Forum.objects.create()
request.put('/api/forum/1/', {'moderators': [{'username': 'JannKleen', }, ], })
```
This should return the new moderator, but instead returns an empty list (the old value of the m2m field).
=> prefetch_related causes api to return outdated data

tastypie/authorization.py, tastypie/compat.py, tastypie/resources.py
`transaction.commit_on_success` and `Options.module_name` are deprecated in Django 1.7 and will be removed in 1.8
=> Django 1.8 compatibility

tastypie/fields.py
Replace django.utils.importlib with python importlib 
"Warning: django.utils.importlib will be removed in Django 1.9"
=> Replace with python importlib

docs/non_orm_data_sources.rst
The example is still missing some but it's nice to show where `Resource` can be imported from.
=> [doc] add missing imports in non-orm example

tastypie/fields.py
Let's do not show this notification:
```
/env/src/django-tastypie/tastypie/fields.py:7: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
from django.utils import datetime_safe, importlib
```
=> RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.

docs/resources.rst, docs/tools.rst
As far as I can tell, the is_authorized method does not exist and is never called
=> Removing documentation references to non-existent method is_authorized

tastypie/resources.py, tests/core/tests/resources.py
Re-created #1082 to reflect new branch/commits. 
This commit adds the field "primary_key" to the resource schema, it can be very useful for auto-generated UI/clients when using explicit primary key columns on your django models.
=> Add 'primary_key' Field To Schema

docs/resources.rst
Spent a good bit of time trying to find out where I could exclude a particular field in the detail view, but only for a POST request, on my model resource. Turned out that `full_dehydrate` had the info I needed but I had no idea what the `for_list` argument was supposed to be so I figured I'd flesh it out a little for the next guy.
=> Elaborate on Resource.full_dehydrate doc

tastypie/fields.py, tests/core/tests/fields.py
float is not permitted as argument type in python 2.6
=> Fixed DecimalField to be compatible with py2.6

tastypie/fields.py
This is necessary because in `apply_sorting` attribute can be only a string, so by first checking for callable and then string in dehydrate, one can define a callable string, which can then be used both in dehydrate and `apply_sorting`.
=> Switch order of check for callable and string

tastypie/fields.py, tests/core/tests/fields.py
Current behavior when invalid data is submitted to `DecimalField.hydrate` is to let the `InvalidOperation` error escape to the top level, resulting in a 500 error. This patch adds tests to ensure that this does not happen and, analogously to invalid date formats, raises an `ApiFieldError`.
=> In DecimalField.hydrate, catch decimal.InvalidOperation and raise ApiFieldError

tastypie/resources.py, tests/related_resource/tests.py
Tastypie ignores extra data sent to a resource, but throws errors if there's extra data on a related resource.
=> Ignore extra related data

docs/serialization.rst
I tried using the example as provided in the current docs, and found that the `to_csv` method didn't work. I've fixed this, based on my own working version. I have to tested the `from_csv` method, but I did check it against the docs, and it appears correct.
The improved example also demonstrates better subclassing of parent Serializer, so the subclass doesn't need to know which formats are already implemented on the parent class.
=> Fixed CSVSerializer example's `to_csv` method to actually work.

tastypie/http.py, tastypie/test.py
This is a tidied up version of the patch in #111 with tests
=> Suppress Content-Type header on HTTP 204 (see #111)

AUTHORS, docs/debugging.rst, docs/serialization.rst, docs/settings.rst, tastypie/serializers.py, tests/core/tests/resources.py, tests/core/tests/serializers.py, tests/core/tests/utils.py
This pull request is a followup on #629. 
I have removed the unimplemented `to_html` and `from_html`. 
This issue solves the problem that text/html is returned where a application/xml or application/json is requested. See details in #629.
I updated tests and docs and added 2 new tests (with Accept header from Chrome/Firefox). The pull request was tested without errors with tox with environments py27, 1.7 and 1.8, py3.4, 1.7 and 1.8.
Please consider incorporating this pull request. 
I also considered implementing the to_html/from_html methods. I could not find a good reference/example where html is used as a serialisation format. For the `to_html` I found the [`_repr_html_`](https://ipython.org/ipython-doc/dev/config/integrating.html#rich-display) in IPython which is appealing, but it's …
=> remove unimplemented to_html/from_html

tox.ini
This removes remaining fork from my PR #1214 in favor of proper PyPI version containing needed fix.
=> Test against latest django-oauth-plus from PyPI

docs/cookbook.rst
`get_children()` method in the example should return multiple objects (if possible) but does not because example code has `child_resource.get_detail(request, parent_id=obj.pk)` instead of `child_resource.get_list(request, parent_id=obj.pk)`.
=> Fixed #1031 - Nested resource example in cookbook returns only one of many possible values

tastypie/bundle.py, tastypie/fields.py, tastypie/resources.py, tests/core/tests/mocks.py, tests/related_resource/api/resources.py, tests/related_resource/api/urls.py, tests/related_resource/models.py, tests/related_resource/tests.py, tests/testcases.py
Related to #1344 
Some test cases have been split up into separate test case to make debugging easier, and some new tests and assertions were added, but otherwise the same tests are being executed.
Notable changes:
1. We skip saving resources loaded via a URI (RelatedField().resource_from_uri()) since we know there's no changes from the client.
2. In RelatedField().resource_from_data(), we no longer check can_update(). We don't use the can_* methods anywhere else, and those methods don't check permissions, just allowed HTTP methods. Permissions checking still happens in Resource().save().
3. In RelatedField().resource_from_data(), we no longer call Resource().obj_update(). It seemed really inappropriate to be saving anything here (during the hydration step), my guess is this code got …
=> Fix hydrating/saving of related resources.

AUTHORS, tastypie/authentication.py
Refs #1395 
In Django 1.9, the `same_origin` function is gone.
Other projects that also got the same issue copied the code from django<1.9: 
https://github.com/jbittel/django-mama-cas/commit/93b74f960b1db4007189a61804cea2089b6d9402
https://github.com/Osmose/django-browserid/commit/afe60218eabf8f19e69e1f7542bc339f009602e1
=> django.utils.http.same_origin not in Django 1.9

README.rst, docs/api.rst, docs/cookbook.rst, docs/index.rst, docs/interacting.rst, docs/resources.rst, docs/tutorial.rst, tastypie/api.py, tastypie/resources.py, tests/alphanumeric/urls.py, tests/authorization/urls.py, tests/basic/urls.py, tests/content_gfk/urls.py, tests/core/tests/api_urls.py, tests/core/tests/field_urls.py, tests/core/tests/manual_urls.py, tests/gis/urls.py, tests/namespaced/api/urls.py, tests/profilingtests/urls.py, tests/slashless/api/urls.py, tests/validation/api/urls.py
Stop using `django.conf.url.patterns`, which will be removed in Django 1.10.
=> stop using django.conf.urls.patterns

AUTHORS, tastypie/serializers.py, tests/basic/tests/views.py
As it currently stands, if a user makes a POST/PUT request with invalidly formatted JSON they receive a response that looks something like this like this:
`{"error":""}`
which, of course, isn't very helpful! This change provides a human readable error message when invalidly formatted JSON is submitted. 
@SeanHayes Hope this helps - let me know if there's anything I can do to improve it.
=> Added error message when JSON requests cannot be deserialized

tastypie/test.py, tests/core/tests/resources.py
Pull out the HTTP No Content assert into a separate method, `assertHttpNoContent`.
Fixes https://github.com/django-tastypie/django-tastypie/issues/1411
=> Split assertHttpAccepted

AUTHORS, docs/interacting.rst, docs/release_notes/dev.rst, tastypie/resources.py, tests/core/tests/fields.py, tests/core/tests/resource_urls.py, tests/core/tests/resources.py
…
Fix for issue #782 (https://github.com/django-tastypie/django-tastypie/issues/782)
Schema information only gives information about whether a related field is
'to_one' or 'to_many', but not about the actual resource type of the field. This
fix adds a new field, called 'related_schema' to the fields schema entry, which
defines the exact type of the related field:
'user': {
[..]
'type': 'related'
'related_type': 'to_one'
'related_schema': '/api/v1/user/schema/'
}
Documentation (schema example on the 'Interacting With The API' page) is updated accordingly.
=> Provide URL of related resource in schema when type="related" (#782)

README.rst, docs/authentication.rst, docs/index.rst, docs/release_notes/v0.11.0.rst, docs/release_notes/v0.9.13.rst, docs/tools.rst, docs/who_uses.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs links for their .org -> .io migration for hosted projects

.travis.yml, tastypie/authentication.py, tastypie/compat.py, tests/core/tests/authentication.py, tox.ini
Adds compatibility for Django 1.10 while retaining backwards compatibility.
Issues discovered:
- Django 1.10 added a check during ModelUserBackend.is_authenticated() to disallow authentication by non-active users.  This makes tastypie's require_active flag no longer relevant while also making it basically impossible to allow non-active users to authenticate without rewriting Django's is_authenticated() method.  This invalidated some tests and also revealed some false-positive tests along the way.  Removing the tests for inactive user authentication caused coverage to drop slightly.
- Tastypie's Authenication.is_authenticated() is a bit of a mess, returning a truthy value (HttpUnauthorized) in some cases.  I feel like we should fix this to be a strictly True/False result and raise/return …
=> Django 1.10

AUTHORS, docs/release_notes/dev.rst, tastypie/migrations/0001_initial.py, tastypie/models.py
In Django 1.9 and before, `on_delete` defaults to `models.CASCADE`, but in Django 2.0 it will be a required argument. This PR simply adds in the argument set to its default, as suggested by this deprecation warning:
```
[...]lib/python2.7/site-packages/tastypie/models.py:35: RemovedInDjango20Warning: on_delete will be a required arg for OneToOneField in Django 2.0. Set it to models.CASCADE on models and in existing migrations if you want to maintain the current default behavior. See https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.ForeignKey.on_delete
user = models.OneToOneField(AUTH_USER_MODEL, related_name='api_key')
```
=> Fix Django 2.0 deprecation warnings

.travis.yml, tests/core/models.py, tests/core/tests/api.py, tests/core/tests/authentication.py, tests/core/tests/fields.py, tests/core/tests/resources.py, tests/run_all_tests.sh, tests/settings.py, tests/settings_core.py, tox.ini
WIP; updating to Django 1.11.
- Remove test matrix for 1.7, 1.9; we should support the most recent version (1.11), the most recent LTE (1.8), and run tests against dev (but allowed to fail).
=> Django 1.11

tests/core/tests/fields.py
MySQLdb returns unicode strings from a column with utf8_bin collation as bytestrings. This causes a `UnicodeDecodeError` when the string is passed to `unicode()`. The problem presents in tastypie when converting `field.CharField` values. This test covers that case by creating a bytestring with unicode characters and passing it to `CharField.convert()`.
This relates to issue #327 and pull request #768
=> Add test for #327

tastypie/fields.py, tests/core/tests/fields.py
I previously [submitted this issue](https://github.com/toastdriven/django-tastypie/pull/269) but closed it because I wanted to refactor the tests.
The current tests located in `tests.core.fields.ApiFieldTestCase.test_dehydrate` test for a lot of conditions, but not when a field has `null=True` and `default=True`.
The logic in `fields.ApiField.dehydrate` specifies that if the field has a `default` then it takes precedence over null (`None`). This means that if you have a Django model like
```
class Comment(models.Model):
times_viewed = models.IntegerField(null=True, default=0)
```
and an object with `times_viewed=None`, `ApiField.dehydrate` will return the default, 0, instead of None.
My patch inverts the checks for a default and null. The default will only be returned if `null=False`.
One …
=> Fields with null=True should dehydrate to None before returning the default

docs/cookbook.rst
change get_detail by get_list.
It's important highlight that parent_id must be available to filtering on ChildResource. I'd like get your opinion.
=> updated example of nested resources by lightly overriding the override_urls method & adding on a new method to handle the children

docs/cookbook.rst
This change brings the cookbook entry on adding search
functionality in-line with the current approach in `get_list`,
enabling proper use of limit and offset parameters, as well
as giving meta-info in requests.
Fixes #661
=> Improve cookbook 'Adding Search Functionality'

tastypie/resources.py, tests/core/tests/resources.py
Addresses recurring not-a-bugs:
#1475, #1517
Note that there's no exception for abstract ModelResource base classes; tastypie doesn't really implement those yet.  I plan to address that in a future PR; for now, they should just set `Meta.queryset = None` and/or `Meta.object_list = None` for now.
=> Add explicit error when ModelResource lacks object_class and queryset

docs/resources.rst, tests/core/tests/resources.py
Docs went out of sync with codebase, discovered this via a stackoverflow question:
https://stackoverflow.com/questions/45129605/build-filters-got-an-unexpected-keyword-argument-ignore-bad-filters
=> Fix Advanced Filtering example; test

docs/resources.rst, tastypie/resources.py, tests/core/tests/resources.py
Implement abstract ModelResources (partly to bypass `object_class` and `queryset` requirements.)
This came out of a prior change to more explicitly detect ModelResources lacking those attributes - the example cases were due to users creating abstract Resources and inheriting from them.
=> Abstract resources

tests/core/tests/__init__.py
Found unexecuted doctests for validating the jsonp callback while researching #1500 part 1;  Explicitly added them to the ``core`` test run.
=> Add validate_jsonp doctests to core suite

tastypie/authentication.py, tastypie/resources.py, tests/core/tests/resources.py
Notes about the changes:
* `tastypie.authentication.Authentication.get_authorization_data` change
This is about re-raising the ValueError with a custom message in case of
.split() returning one item (instead of two). Made it explicit.
* `tastypie.resources.BaseModelResource.obj_update` change
I left this as is, because pinpointing **all the possible exceptions** that
may be raised during data hydration is error-prone. "# flake8: noqa"
prevents flake8 error.
* `tests.core.tests.resources.ResourceTestCase.test_auth_check` change
BasicResource.is_authenticated() (without a custom authentication defined
in "meta") can only raise ImmediateHttpResponse exception. Catch it
explicitly.
* `tests.core.tests.resources.ModelResourceTestCase.test_is_valid` change
Current implementation of …
=> Deal with bare except statements. See #1540.

tastypie/resources.py, tests/core/tests/resources.py
This is a resubmitted fix proposed by @aaronelliotross. See issue page https://github.com/django-tastypie/django-tastypie/issues/1489 for discussion on resubmitting pull request. 
Original commit:
https://github.com/aaronelliotross/django-tastypie/commit/bd46c5a1a348e84e9c01f90f71bf49afd3c5c5e4
Original pull request:
https://github.com/django-tastypie/django-tastypie/pull/1494.
=> Reorder blank, null checks in full_hydrate - #1489

AUTHORS, tastypie/resources.py, tests/core/tests/resources.py
This solves Issue: https://github.com/django-tastypie/django-tastypie/issues/1547 in a different way that https://github.com/django-tastypie/django-tastypie/pull/701 since I use the already existing method obj_get_list to get a queryset and then filter that by the required ids.
=> Get multiple in one query

tastypie/fields.py, tests/core/tests/fields.py
Probably fixes #1537 but the full extent of that issue remains unclear.  I'd like to add a test for a proper request/response (rather than the extremely simplified test of `dehydrate()`) but I am waiting for enough information in that ticket to reproduce the bug in a real-world situation.
=> Fix for ToManyField.dehydrate with a null value regression.

tastypie/paginator.py, tests/core/tests/paginator.py
As noted in the target branch:
This test is failing:
FAIL: test_multiple (core.tests.paginator.PaginatorTestCase)
This is due to a regression in django 2.1.  There's a fix here but it hasn't been released yet:
https://github.com/django/django/commit/d8e2be459f97f1773c7edf7d37de180139146176
Note that it says "due to lazily-written tests" and I generally agree; `QueryDict` when populated from an actual HTTP request will always be strings, not ints, and our tests should be written to reflect that.
=> 'Fix' for upstream regression regarding non-string query params in tests

README.rst
shields.io doesn't support pypi downloads any more
=> Fix pypi downloads badge

tastypie/fields.py, tests/core/tests/resources.py
Rebased the changeset from #1482, a proposed fix for `contribute_to_clase` failing when `attribute` is not a string.
=> Port fix from #1482

tastypie/validation.py
...ationships to work when using CleanedDataFormValidation with django ORM models that have Related fields
Formerly, when an insert or update operation occurs on a model that uses a FK relationship field in the form, TastyPie would pass into the form validation the URI that was provided in bundle.data.  Unfortunately, Django really wants a PK reference (the output of model_to_dict, in this case) and would fail in such cases.  This fix detects those related fields in the target model (bundle.obj) and leaves the references to the related table intact, but still applies bundle values for all other fields (some of which might not be in the model, but might be required for the form.)
=> Update to Allow CleanedDataFormValidation to work with forms/models that have related fields.

docs/authorization.rst
Looks like missed <id> param
https://django-tastypie.readthedocs.io/en/latest/authorization.html#authorization-options
=> authorization docs: missed <id> for delete_detail

.github/workflows/python-package.yml, AUTHORS, README.rst, docs/cookbook.rst, tastypie/authentication.py, tastypie/compat.py, tests/core/tests/authentication.py, tox.ini
Django 4.1 has changed the name of _sanitize_token to _check_token_format - handle the case(s) where the new name is required to be imported, rather than the old one.
This is identified in ticket #1640
=> Update to support Django 4.1

.github/workflows/python-package.yml, README.rst, tox.ini
TastyPie v0.14.5 is already compatible with Django 4.2, but the readme and test matrix needs to be updated to reflect that.
=> Django 4.2 compatibility

.github/workflows/python-package.yml, AUTHORS, README.rst, docs/cookbook.rst, tastypie/authentication.py, tastypie/compat.py, tastypie/utils/timezone.py, tests/core/tests/authentication.py, tests/core/tests/resources.py, tests/settings.py, tox.ini
This change adds in support for Django 5.0 in Tastypie by doing the following:
1.  Add in a compatability function.
2. Update the tests to properly indicate the versions of python and django suitable for testing with this release.
3. Ensure that tox tests pass properly.
> Running Sphinx v7.2.6
> making output directory... done
> building [mo]: targets for 0 po files that are out of date
> writing output... 
> building [doctest]: targets for 51 source files that are out of date
> updating environment: [new config] 51 added, 0 changed, 0 removed
> reading sources... [100%] who_uses
> looking for now-outdated files... none found
> pickling environment... done
> checking consistency... done
> running tests...
> 
> Document: cookbook
> ------------------
> 1 items passed all tests:
>   16 …
=> Add in support for Django 5.0 by adding in compat functionality for datetime_safe

tests/core/tests/__init__.py
@georgedorn I think the answer is much simpler, it doesn't fail because i failed to add it to the __init_ and thus it didn't get discovered. 
I'm PRing this to your bug branch.
=> Add race condition tests to core innit.

tastypie/resources.py, tests/core/models.py, tests/core/tests/__init__.py, tests/core/tests/api.py, tests/core/tests/api_urls.py, tests/core/tests/race_condition.py
Manually rebasing @quietlyconfident's work in #1151 against the current release, in case anybody is interested in picking it back up.  I took an educated guess about how to merge that code into the current release; some of `BaseModelResource.save()` has already changed, but I cannot guarantee my guess is correct as I cannot replicate the issue.
Thus, the process for getting this merged:
1. Test this in a scenario known to cause the issue, to make sure my guess about merging is correct, and fix it if not.
2. Fix the current failing tests, making sure the new code doesn't introduce regressions.  It is possible the new code is the wrong way to do this.
3. Write new tests covering this new behavior; it would be nice if the race condition could be replicated via the live server test cases, but …
=>  Fix race condition between POST / PATCH resources by using update_fields... #1151  Rebuilt against  v0.14.7.

tests/core/tests/resources.py, tests/namespaced/tests.py
Both TestCase.assert_() and TestCase.assertEquals() have been deprecated since Python 3.2, and removed as of Python 3.12. Switch to the correct method names, assertIn() and assertEqual().
=> Use non-deprecated assertion methods
