django-tastypie/django-tastypie

tastypie/authentication.py

Getting the header value for key `HTTP_AUTHORIZATION` only once for this method

Small optimization of `extract_credentials` method

---

docs/release_notes/v0.9.16.rst

See commit for details: https://github.com/django-tastypie/django-tastypie/commit/abc0bef

PUT response code correction

---

docs/resources.rst

See commit for details: https://github.com/django-tastypie/django-tastypie/commit/abc0bef

Update PUT response codes

---

tests/manage_profilingtests.py
tests/profilingtests/tests.py
tests/settings_profilingtests.py

This test is useful for evaluating how proposed optimizations affect the generation an entire response.

Added profilingtests.

---

tests/core/tests/resources.py

Tastypie sends back data in PUT

Tastypie sends back data in PUT

---

tastypie/fields.py
tastypie/serializers.py
tests/core/tests/fields.py
tests/core/tests/resources.py

I found some code that was storing data directly on Field objects, which get reused between requests. This ablity was undocumented and untested, and could lead to unpredicatable behavior if someone tried to use it.

Data leakage fix

---

tastypie/resources.py
tests/core/tests/resources.py

Hage master3108 bugfix/issue 1354 fix resource deserialize params

---

docs/interacting.rst
tastypie/api.py
tastypie/resources.py
tastypie/utils/__init__.py
tests/core/tests/api.py
tests/core/tests/resources.py
tests/core/tests/utils.py
tests/core/utils.py

Optionally retrieve all schemas in a single request.

Full schema

---

AUTHORS
docs/testing.rst
tastypie/test.py

Add ResourceTransactionTestCase and mixin.

---

AUTHORS
docs/release_notes/dev.rst
tastypie/bundle.py
tests/basic/tests/resources.py

Attach pull-request for issue #1421.
I'll be glad to listen any objections or suggestions! Thanks for your time!

Changed repr value for Bundle to str in PY2

---

AUTHORS
README.rst
docs/code/myproject/urls.py
docs/cookbook.rst
docs/namespaces.rst
docs/non_orm_data_sources.rst
docs/release_notes/dev.rst
docs/resources.rst
docs/testing.rst
docs/tutorial.rst
tastypie/authorization.py
tastypie/models.py
tastypie/resources.py
tastypie/test.py
tests/core/fixtures/note_testdata.json
tests/core/tests/resource_urls.py

Cleaning up old, unneeded code.

---

docs/paginator.rst

Fix little typo in docs example

---

tastypie/resources.py

https://github.com/django-tastypie/django-tastypie/issues/1473

Fix #1473. Incompatibility with Django-Channels

---

tastypie/utils/mime.py
tests/core/tests/api.py

Piggybacking on #1233's fix since I don't know if he still has a vested interest in trying to merge my tests in, but I just discovered this and it's quite concerning.

JSONP security fix + tests

---

docs/resources.rst

resources docs: serializated -> serialized

---

tastypie/utils/urls.py
tastypie/utils/validate_jsonp.py

I think this is all that was failing on https://github.com/django-tastypie/django-tastypie/pull/1507

Fixed failing flake8 tests

---

docs/non_orm_data_sources.rst

Sorry for the pedantic PR, but I love tastypie.

Delete extraneous all in documentation

---

docs/release_notes/v0.14.0.rst

https://github.com/django-tastypie/django-tastypie/commit/09a29fdb80c6c6f8d4eb80e538ba1d4cd1e96732

0.14.0 changelog: add note for removing ResourceTestCase

---

tastypie/resources.py

Fix incorrect docstring pointed out by @cheng10.

Fix docstring for put_list

---

.travis.yml
tests/settings.py
tox.ini

WIP branch for implementing django 2.0 support.

Set up CI tests for Django 2.0

---

docs/code/myapp/models.py
docs/code/myproject/wsgi.py
docs/conf.py
setup.cfg
tastypie/authentication.py
tastypie/compat.py
tastypie/resources.py
tastypie/serializers.py
tastypie/utils/__init__.py
tastypie/utils/formatting.py
tastypie/utils/validate_jsonp.py
tests/alphanumeric/tests/__init__.py
tests/basic/tests/__init__.py
tests/content_gfk/tests/__init__.py
tests/core/tests/__init__.py
tests/customuser/tests/__init__.py
tests/gis/tests/__init__.py
tests/settings_alphanumeric.py
tests/settings_authorization.py
tests/settings_basic.py
tests/settings_content_gfk.py
tests/settings_core.py
tests/settings_customuser.py
tests/settings_gis.py
tests/settings_gis_spatialite.py
tests/settings_namespaced.py
tests/settings_profilingtests.py
tests/settings_related.py
tests/settings_slashless.py
tests/settings_validation.py

Fixes for shuffles in flake8 and/or travis.

Ignore flake8 for tests dir

---

docs/cookbook.rst
docs/fields.rst
docs/resources.rst

Signed-off-by: Abhishek Kumar Singh <abhishek4bhopati@gmail.com>

Fix invalid tuple modification and other doc fixes (fixing rst). 

---

tastypie/resources.py
tests/core/tests/resources.py

lookup_kwargs_with_identifiers: handle detail_uri_name specially

---

README.rst

readme: Update supported versions

---

.travis.yml
tastypie/api.py
tastypie/authentication.py
tastypie/compat.py
tests/core/tests/__init__.py
tests/core/tests/resources.py
tests/requirements.txt
tests/settings.py
tox.ini

Merging various downstream contribs.

Feature/django 3.2

---

tastypie/resources.py
tests/core/migrations/0001_initial.py
tests/core/models.py
tests/core/tests/resources.py

Issue: https://github.com/django-tastypie/django-tastypie/issues/1620

Add support for BigAutoField in ModelResource

---

tastypie/authentication.py
tests/core/tests/authentication.py

Fixed crash when missing CSRF token cookie in SessionAuthentication

---

tests/core/models.py
tests/core/tests/api.py
tests/core/tests/api_urls.py
tests/core/tests/race_condition.py

The SlowNotes model/resource, although not strictly needed for the test avoids flakiness.

Add test for #1151 Fix race condition between POST / PATCH resources.
